bugfix: Database create failed.
Something is wrong with the new anko, so I downgrade anko and kotlin.
Detail is here: <a
href="https://github.com/Kotlin/anko/issues/409">Caused by:
android.database.sqlite.SQLiteException: near “org”: syntax error (code
        1): , while compiling: · Issue #409 · Kotlin/anko</a>